blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import post_list, post_detail,  catwise_post, category_list, update_category, delete_category, create_category, blog_post_list, blog_post_detail, update_blog_post, delete_blog_post, create_blog_post

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='home'),
    path('<slug:slug>', post_detail, name='post-detail'),
    path('catwise/post/<str:cat_name>', catwise_post, name='catwise-post'),
    path('category/list', category_list, name='category-list'),
    path('update/category/<int:id>', update_category, name='update-category'),
    path('delete/category/<int:id>', delete_category, name='delete-category'),
    path('create/category', create_category, name='create-category'),

    path('post/list', blog_post_list, name='blog-post-list'),
    path('post/detail/<int:id>', blog_post_detail, name='blog-post-detail'),
    path('update/post/<int:id>', update_blog_post, name='update-blog-post'),
    path('delete/post/<int:id>', delete_blog_post, name='delete-blog-post'),
    path('create/blog/post', create_blog_post, name='create-blog-post'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from .views import user_login, user_logout 
from users.views import profile, contact, contact_list, contact_details, create_about, show_about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/preferences', TemplateView.as_view(template_name='admin/preferences.html')),
    path('', include('blog.urls')),

    path('profile/admin/', profile, name='profile'),
    path('contact/form', contact, name='contact'),
    path('contact/list', contact_list, name='contact-list'),
    path('contact/details/<int:id>', contact_details, name='contact-details'),

    path('create/about', create_about, name='create-about'),
    path('show/about', show_about, name='about'),

    path('summernote/', include('django_summernote.urls')),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{% url 'profile' as profile_url %}


{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #44B78B;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
        .navbar-expand-lg {
            background-color: #0C4B33 !important;
        }
        
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand text-light font-weight-bold" href="{% url 'blog:home' %}">{{ brand_name }}</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link {% if request.path == home_url %} active {% endif %} text-light font-weight-bold" href="{% url 'blog:home' %}"><small>HOME</small></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link {% if request.path == about_url %} active {% endif %} text-light font-weight-bold" href="{% url 'about' %}"><small>ABOUT</small></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link {% if request.path == contact_url %} active {% endif %} text-light font-weight-bold" href="{% url 'contact' %}"><small>CONTACT</small></a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item ">
                            <a class="nav-link {% if request.path == profile_url %} active {% endif %} text-light font-weight-bold" href="{% url 'profile' %}"><small>PROFILE</small></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active text-light font-weight-bold" href="/admin/preferences"><small>ADMIN</small></a>
                        </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <!-- admin preferences -->
                        
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == logout_url %} active {% endif %} text-light font-weight-bold" href="{% url 'logout' %}"><small>LOGOUT</small></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == login_url %} active {% endif %} text-light font-weight-bold" href="{% url 'login' %}"><small>LOGIN</small></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey mt-5">
            <p class="m-0 text-dark text-center ">Copyright &copy; AVIJEET'S BLOG</p>
        </footer>
    </body>
</html>

templates/base/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4 ">
        
        <div class="card-body">
          <form action="" method="GET">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search a keyword ..." name="s">&nbsp;
              
              <!--
  <span class="input-group-btn">
                <button class="btn btn-secondary" type="Submit">Go!</button>
              </span>
              -->
            </div>
          </form>
          
        </div>
      </div>
<div class="card my-4">
        <h5 class="card-header">Category</h5>
    <div class="card-body">
      <ul class="list-unstyled mb-0">
        {% for c in cat %}
          <li>
            <a href="{% url 'blog:catwise-post' c.name %}">{{ c.name }}</a>
          </li>
        {% endfor %}
        
        
      </ul>
    </div>
</div>
</div>

{% endblock sidebar %}